server {

listen 80;


root /usr/share/nginx/html;


location / {


    try_files $uri $uri/ =404;

}


location /count {


    default_type text/plain;


    content_by_lua_block {

        local file="/tmp/count"


        local f=io.open(file,"r")

        local n=0


        if f then
            n=tonumber(f:read("*a")) or 0
            f:close()
        end


        n=n+1


        f=io.open(file,"w")
        f:write(n)
        f:close()


        ngx.say(n)

    }

}


}
