# SonarQube 项目唯一标识
sonar.projectKey=nginx-test

# SonarQube 显示名称
sonar.projectName=nginx-test

# 项目版本
sonar.projectVersion=1.0

# 源码目录
sonar.sources=.

# 排除不扫描内容
sonar.exclusions=\
k8s/**,\
.github/**,\
*.yaml,\
*.yml

# 编码
sonar.sourceEncoding=UTF-8
