apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-test.fullname" . }}
spec:
  selector:
    app: nginx-test
  ports:
  - name: http
    port: 80
    targetPort: http
  type: {{ .Values.service.type }}