name: nginx-test CI/CD
on:
  push:
    branches:
      - master

  workflow_dispatch:
env:
  IMAGE_NAME: ${{ vars.HARBOR_URL }}/${{ vars.HARBOR_PROJECT }}/nginx-test
  KUBECONFIG: /root/.kube/config

jobs:

# ==========================================================
# SonarQube Code Scan
# ==========================================================
  sonar:
    name: SonarQube Scan
    runs-on:
      - self-hosted
      - linux
      - docker

    environment:
      name: dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

# ==========================================================
# Build Docker Image
# Push Harbor
# ==========================================================

  build:
    name: Build And Push Image
    runs-on:
      - self-hosted
      - linux
      - docker
    environment:
      name: dev
    needs:
      - sonar
    outputs:
      image_tag: ${{ steps.version.outputs.tag }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Image Tag
        id: version
        run: |
          TAG=$(git rev-parse --short HEAD)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "IMAGE TAG=$TAG"
    

      - name: Login Harbor
        env:
          HARBOR_USER: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
        run: |
          docker logout harbor.azhuan.ren || true
          echo "$HARBOR_PASSWORD" | docker login -u "$HARBOR_USER" --password-stdin harbor.azhuan.ren


      - name: Docker Build
        run: |
          docker build \
          --build-arg BUILD_HASH=${{ steps.version.outputs.tag }} \
          -t $IMAGE_NAME:${{ steps.version.outputs.tag }} \
          .

      - name: Push Harbor
        run: |
          docker push \
          $IMAGE_NAME:${{ steps.version.outputs.tag }}

# ==========================================================
# K3s Deploy
# ==========================================================

  deploy:
    name: Deploy K3s
    runs-on:
      - self-hosted
      - linux
      - docker

    environment:
      name: dev
    needs:
      - build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Image Tag
        run: |
          TAG=$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Helm Upgrade And Install
        run: |
          docker run --rm \
            --network host \
            -e KUBECONFIG=/root/.kube/config \
            -v /root/.kube/config:/root/.kube/config:ro \
            -v "$GITHUB_WORKSPACE":/workspace \
            -w /workspace \
            alpine/helm:3.19.0 \
            upgrade --install nginx-test ./helm/nginx-test \
            --namespace default \
            --set image.repository="$IMAGE_NAME" \
            --set image.tag="$IMAGE_TAG"

      - name: Rollout Status
        run: |
          docker run --rm \
            --network host \
            -e KUBECONFIG=/root/.kube/config \
            -v /root/.kube/config:/root/.kube/config:ro \
            bitnami/kubectl:latest \
            rollout status \
            deployment/nginx-test-nginx-test \
            --timeout=180s

      - name: Verify Deployment
        run: |
          docker run --rm \
            --network host \
            -e KUBECONFIG=/root/.kube/config \
            -v /root/.kube/config:/root/.kube/config:ro \
            bitnami/kubectl:latest \
            get deployment nginx-test-nginx-test

          echo ""
          echo "========================"
          echo "Pods"
          echo "========================"

          docker run --rm \
            --network host \
            -e KUBECONFIG=/root/.kube/config \
            -v /root/.kube/config:/root/.kube/config:ro \
            bitnami/kubectl:latest \
            get pods \
            -l app=nginx-test \
            -o wide

          echo ""
          echo "========================"
          echo "Current Image"
          echo "========================"

          docker run --rm \
            --network host \
            -v /root/.kube/config:/root/.kube/config:ro \
            bitnami/kubectl:latest \
            get deployment nginx-test-nginx-test \
            -o jsonpath='{.spec.template.spec.containers[0].image}'

          echo
