name: nginx-test CI/CD
on:
  push:
    branches:
      - master

  workflow_dispatch:
env:
  IMAGE_NAME: ${{ vars.HARBOR_URL }}/${{ vars.HARBOR_PROJECT }}/nginx-test
  KUBECONFIG: /root/.kube/config

jobs:

# ==========================================================
# SonarQube Code Scan
# ==========================================================
  sonar:
    name: SonarQube Scan
    runs-on:
      - self-hosted
      - linux
      - docker

    environment:
      name: dev

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

# ==========================================================
# Build Docker Image
# Push Harbor
# ==========================================================

  build:
    name: Build And Push Image
    runs-on:
      - self-hosted
      - linux
      - docker
    environment:
      name: dev
    needs:
      - sonar
    outputs:
      image_tag: ${{ steps.version.outputs.tag }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Image Tag
        id: version
        run: |
          TAG=$(git rev-parse --short HEAD)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "IMAGE TAG=$TAG"
      
      - name: Test Harbor Login
        run: |
          echo "Harbor URL=${{ vars.HARBOR_URL }}"
          echo "Username=${{ secrets.HARBOR_USERNAME }}"
          echo "${{ secrets.HARBOR_PASSWORD }}" | \
          docker login \
          "${{ vars.HARBOR_URL }}" \
          -u "${{ secrets.HARBOR_USERNAME }}" \
          --password-stdin

      - name: Login Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | \
          docker login \
          "${{ vars.HARBOR_URL }}" \
          -u "${{ secrets.HARBOR_USERNAME }}" \
          --password-stdin

      - name: Docker Build
        run: |
          docker build \
          --build-arg BUILD_HASH=${{ steps.version.outputs.tag }} \
          -t $IMAGE_NAME:${{ steps.version.outputs.tag }} \
          .

      - name: Push Harbor
        run: |
          docker push \
          $IMAGE_NAME:${{ steps.version.outputs.tag }}

# ==========================================================
# K3s Deploy
# ==========================================================

  deploy:
    name: Deploy Kubernetes
    runs-on:
      - self-hosted
      - linux
      - docker

    environment:
      name: dev
    needs:
      - build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Image Tag
        run: |
          TAG=$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      # 修改 deployment 镜像

      - name: Update Kubernetes Image
        run: |
          sed -i \
          "s#image: .*nginx-test:.*#image: $IMAGE_NAME:$IMAGE_TAG#" \
          k8s/deployment.yaml

      - name: Show Kubernetes YAML
        run: |
          cat k8s/deployment.yaml

      # 发布 k8s

      - name: Apply Kubernetes
        run: |
          kubectl apply -f k8s/

      - name: Rollout Status
        run: |
          kubectl rollout status \
          deployment/nginx-test \
          --timeout=180s

      - name: Verify Deployment
        run: |
          echo "========================"
          echo "Deployment"
          echo "========================"
          kubectl get deployment nginx-test

          echo ""
          echo "========================"
          echo "Pods"
          echo "========================"

          kubectl get pods \
          -l app=nginx-test \
          -o wide

          echo ""
          echo "========================"
          echo "Current Image"
          echo "========================"

          kubectl get deployment nginx-test \
          -o jsonpath='{.spec.template.spec.containers[0].image}'

          echo
